### PR TITLE
Clarify websockets

### PR DESCRIPTION
**Pull request by pwalczysko**
As discussed recently, add a clarification about usefulness of websockets into the guide.

This is a complement to the adjustment of the signup email on demo server which is implemented in  https://github.com/ome/prod-playbooks/pull/379  in commit https://github.com/ome/prod-playbooks/pull/379/commits/c1461feda8d6ad479f41863f09b44149139e8afd

cc @dominikl @jburel

### CODE REVIEW

**Comment by dominikl** [comment]
Generally 👍 as it mentions websockets already as an option `...or connect using websockets.`. I just wonder if it needs another caveat like "if your institution has set up websocket for OMERO". I don't think enabling websockets is part of the standard OMERO installation procedure, is it?

**Comment by pwalczysko** [comment]
> Generally 👍 as it mentions websockets already as an option `...or connect using websockets.`. I just wonder if it needs another caveat like "if your institution has set up websocket for OMERO". I don't think enabling websockets is part of the standard OMERO installation procedure, is it?

@dominikl thanks. I have clarified in https://github.com/ome/omero-guide-upload/pull/18/commits/d28471ad2401281bda42c2b4178fec7447b854f7

**Review by dominikl — APPROVED** [review]
👍

**Comment by pwalczysko** [comment]
Build looks good. Thank you @dominikl . Merging.

**Pull request merged**
